### PR TITLE
Better emissions comparisons

### PR DESCRIPTION
**Pull request by benoit-cty**
I change the computation of the metrics because I think they were wrongs.

Before:
image

After:
image

I had comments in the code on how I made the computation.

I also change the deployment config to push it to CleverCloud production : https://dashboard.codecarbon.io/

### CODE REVIEW

**Review by inimaz — APPROVED** [review]
Looks good, thanks! And thanks for the comments, they help with the calculus. Should we mention somewhere the year and source for the constants: car emissions, household emissions, TV emissions... ?

**Comment by sashavor** [comment]
Maybe we can cite some official source(s), like the EPA? https://www.epa.gov/energy/greenhouse-gases-equivalencies-calculator-calculations-and-references

**Comment by SaboniAmine** [comment]
Can we close this PR now ?

**Comment by benoit-cty** [comment]
Yes, it was on the old dashboard. And we do better in the new one.

**Pull request closed without merging**
