### PR TITLE
update the CSV every 8 x 15 seconds

### LINKED ISSUE #467: Capture measurements in CSV based on time intervals
* CodeCarbon version: 2.2.2
* Python version: 3.11.5
* Operating System: Linux-6.2.0-35-generic-x86_64-with-glibc2.35

### Description

I have implemented a method that enables the capture and storage of consumption logs (CSV format) in parallel every second during the execution of my algorithm. Nevertheless, I would be interested in exploring whether there are more efficient alternatives from a technical or academic standpoint to accomplish this process. Below, I am providing the code of my current solution for review and suggestions.

### What I Did

```
from codecarbon import EmissionsTracker
import threading

pthread=1
def fthread():
    while pthread:
        tracker.flush()
        time.sleep(1)

# Creates an instance of a thread and passes the function is executed.
eng_measure = threading.Thread(target=fthread)

# Training 
tracker = EmissionsTracker(project_name="Test",tracking_mode="machine")
tracker.start()
eng_measure.start()
try:
    # code
finally:
    pthread = 0
    eng_measure.join()
    emissions = tracker.stop()
```

### PR DESCRIPTION
**Pull request by olamidepeterojo**
This fixes #467

### CODE REVIEW

**Review by benoit-cty — CHANGES_REQUESTED** [review]
Could you please remove all files from activate folder?

**Comment by olamidepeterojo** [comment]
i've done that in #708

**Review by SaboniAmine — CHANGES_REQUESTED** [review]
Could you also describe how would you solve the issue linked ? 
Your current additions do not fit with the way the tracker works, and would introduce some incorrect behaviors in the main logic.

**Comment by SaboniAmine** [comment]
Closing this stale PR, please describe your change request, we'll re-open if needed!

**Pull request closed without merging**
