### PR TITLE
Import Github actions and contributions configuration from co2-tracker-utils

### PR DESCRIPTION
**Pull request by Lothiraldan**
This PR contains a copy of the Github actions used for https://github.com/comet-ml/co2-tracker-utils.

It contains:
- Packaging actions + Conda meta.yaml package definition. The upload part is currently missing from the Github action.
- Release drafter github actions to prepare a draft of a release note for each PR merged, very helpful.
- Pre-commit Github action + pre-commit configuration (https://pre-commit.com/). This helps enforcing style-guide and running linting. We should probably update the Readme to ask people to use it.
- Run the tests with tox.

### CODE REVIEW

**Comment by vict0rsch** [comment]
Should we merge @Lothiraldan ?

**Comment by Lothiraldan** [comment]
Sure I can remove the flake-8 copyright and flake8-coding plugins so the build will pass.

**Comment by Lothiraldan** [comment]
Ok that should be ready for review now, it seems that the tests are failing, in part because the test machine doesn't have a GPU.

**Comment by vict0rsch** [comment]
@Lothiraldan Any idea why the fails?

**Comment by Lothiraldan** [comment]
No idea, the tests are green locally.

**Comment by vict0rsch** [comment]
@kngoyal  any idea why tests would fail on 3.8 but not 3.6 or 3.7?

**Comment by Lothiraldan** [comment]
This might be a flaky test caused by some timing issues, we can change the flaky test from:

```
          self.assertEqual(
              3, mocked_get_gpu_details.call_count
          )
```

to:

```
          self.assertGreaterEqual(
              3, mocked_get_gpu_details.call_count
          )
```

**Comment by vict0rsch** [comment]
@kngoyal thoughts?

**Review by kngoyal — APPROVED** [review]

**Comment by vict0rsch** [comment]
Thanks @kngoyal

**Pull request merged**
