### PR TITLE
Fixed typo in usage docs

### PR DESCRIPTION
**Pull request by dsblank**
Misspelled CODECARBON

### CODE REVIEW

**Review by SaboniAmine — APPROVED** [review]
Thanks for the contribution!

**Comment by dsblank** [comment]
@SaboniAmine Something unrelated seems to be failing, preventing me from merging this.

**Comment by SaboniAmine** [comment]
One failing test may be related to #370, seems to be the same behavior. 
API test fail seems related to the fix you made @benoit-cty.
We'll check that before merging ourselves, @dsblank; thanks!

**Comment by benoit-cty** [comment]
I will fix the errors in https://github.com/mlco2/codecarbon/pull/374

**Pull request merged**
