### PR TITLE
Update emissions_tracker.py to fix issue  #549

### PR DESCRIPTION
**Pull request by LeahChercham**
Update emissions_tracker.py to fix issue  #549 Divide by zero in start_task() by replacing time.time() by time.perf_counter()

Replaced all time.time() by time.perf_counter() in file emissions_tracker.py.

perf_counter gets the current time with higher precision.

### CODE REVIEW

**Review by SaboniAmine — APPROVED** [review]
LGTM, thanks!

**Comment by LeahChercham** [comment]
Hi @benoit-cty I deleted the forked-repo from my profile, is this a problem or where you able to get the changes of my pull request anyway ? (Sorry this is my first time contributing to a project)

**Comment by benoit-cty** [comment]
Yes it's a problem :
image

But your code still appear there : https://github.com/mlco2/codecarbon/pull/570/files if you want to restore it.

You could delete the fork only after we merge the code to the master of CodeCarbon.

**Comment by LeahChercham** [comment]
I wasn't able to restore so I recreated this pull request: https://github.com/mlco2/codecarbon/pull/589

**Pull request closed without merging**
