### PR TITLE
fixed trailing commas for 3.5, 3.6+

### PR DESCRIPTION
**Pull request by marksmayo**
had to re-run black after to reformat as well, due to the commas

also pre-commit flake requires gitlab, which I don't have an account for, but I've run it manually as best I can

### CODE REVIEW

**Comment by benoit-cty** [comment]
Hello, thanks for your contribution.
I don't understand why Black make so many changes as we already run Black in pre-commit. Does the default behavior changed ?
Do you have an explanation ?

**Comment by marksmayo** [comment]
I'm not sure myself, I was wondering too. Maybe it's running against a different version of python / black? I'm on python 3.11

**Comment by SaboniAmine** [comment]
Hello,
About pre-commit, the flake8 project have been moved to github recently, as Benoît kindly informed me. See [this discussion](https://www.reddit.com/r/Python/comments/yvfww8/flake8_took_down_the_gitlab_repository_in_favor/). If needed, you can rebase [this commit](https://github.com/mlco2/codecarbon/pull/356) to your branch to have the correct configuration.

**Comment by marksmayo** [comment]
Hmm, conflicts and that query over black changing lots. I think I'll redo it instead. Hope that's ok

**Comment by benoit-cty** [comment]
Thank's, that's OK.

**Pull request closed without merging**
