### PR TITLE
feat: prometheus pushgateway mode

### PR DESCRIPTION
**Pull request by inimaz**
Related to #162.
This PR pushes `codecarbon` metrics to a given [Prometheus pushgateway](https://github.com/prometheus/client_python#exporting-to-a-pushgateway).

See the [README](https://github.com/mlco2/codecarbon/blob/e33a7e35025a4f9ee73a5265aaac38f4eb0c1db8/codecarbon/prometheus/README.md) for how to use it.

### CODE REVIEW

**Review by benoit-cty — CHANGES_REQUESTED** [review]
Thanks a lot for this great improvement !
Can you add `save_to_prometheus` and `prometheus_url` to `def track_emissions(` ?
So we could use it with decorator.
(maybe you could find a way to avoid duplicating code in track_emissions)

**Comment by inimaz** [comment]
Done that!
See ac1107f08c30940a1e6457140cda3887a2ce3596.
As well there is a test that is always failing (the one with the default-cpu-constant). It fails because sometimes it finds the cpu's TDP in the list of `data/hardware/cpu_power.csv`. And for that test to pass I need the machine to not be in that list :( 
For now as a quick fix I have commented it out (4f62cad1f308c846b70f6c514a5b4525657f1852). But best way it would be to arrive to mock the file when running the test.

**Comment by inimaz** [comment]
> Done that! See [ac1107f](https://github.com/mlco2/codecarbon/commit/ac1107f08c30940a1e6457140cda3887a2ce3596). As well there is a test that is always failing (the one with the default-cpu-constant). It fails because sometimes it finds the cpu's TDP in the list of `data/hardware/cpu_power.csv`. And for that test to pass I need the machine to not be in that list :( For now as a quick fix I have commented it out ([4f62cad](https://github.com/mlco2/codecarbon/commit/4f62cad1f308c846b70f6c514a5b4525657f1852)). But best way it would be to arrive to mock the file when running the test.



> Done that! See [ac1107f](https://github.com/mlco2/codecarbon/commit/ac1107f08c30940a1e6457140cda3887a2ce3596). As well there is a test that is always failing (the one with the default-cpu-constant). It fails because sometimes it finds the cpu's TDP in the list of `data/hardware/cpu_power.csv`. And for that test to pass I need the machine to not be in that list :( For now as a quick fix I have commented it out ([4f62cad](https://github.com/mlco2/codecarbon/commit/4f62cad1f308c846b70f6c514a5b4525657f1852)). But best way it would be to arrive to mock the file when running the test.



> Done that! See [ac1107f](https://github.com/mlco2/codecarbon/commit/ac1107f08c30940a1e6457140cda3887a2ce3596). As well there is a test that is always failing (the one with the default-cpu-constant). It fails because sometimes it finds the cpu's TDP in the list of `data/hardware/cpu_power.csv`. And for that test to pass I need the machine to not be in that list :( For now as a quick fix I have commented it out ([4f62cad](https://github.com/mlco2/codecarbon/commit/4f62cad1f308c846b70f6c514a5b4525657f1852)). But best way it would be to arrive to mock the file when running the test.

**Comment by inimaz** [comment]
@benoit-cty Could you check this when you have the time?  All tests are passing now.

**Review by benoit-cty — APPROVED** [review]
Sorry for the delay and thanks a lot for this great new feature !

**Comment by LukasFehring** [comment]
The documentation of the output features has not been adapted accordingly https://mlco2.github.io/codecarbon/parameters.html#output-parameters

**Comment by ipower-cc** [comment]
setup.py seems to missing the promethus_client dependency.
When I import a downstream package such as flask-sustainable:

` File "/home/ccc/ipower/webconsole/.venv/lib/python3.11/site-packages/codecarbon/__init__.py", line 6, in <module>
    from .emissions_tracker import (
  File "/home/ccc/ipower/webconsole/.venv/lib/python3.11/site-packages/codecarbon/emissions_tracker.py", line 27, in <module>
    from codecarbon.output import (
  File "/home/ccc/ipower/webconsole/.venv/lib/python3.11/site-packages/codecarbon/output.py", line 22, in <module>
    from codecarbon.prometheus.prometheus import Prometheus
  File "/home/ccc/ipower/webconsole/.venv/lib/python3.11/site-packages/codecarbon/prometheus/prometheus.py", line 3, in <module>
    from prometheus_client import push_to_gateway
ModuleNotFoundError: No module named 'prometheus_client'`

I don't see an extras option aside from 'viz' and 'dashboard'

**Comment by benoit-cty** [comment]
Yes, sorry for that, I quick-fixed it in : https://github.com/mlco2/codecarbon/pull/422/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
But it will be better to have an extra.

**Pull request merged**
