### PR TITLE
fix: scatter chart shows correct timestamp

### PR DESCRIPTION
**Pull request by inimaz**
Closes https://github.com/mlco2/codecarbon/issues/724.

Improvements in scatter chart:

- Sort data by timestamp
- Correct timestamp displayed
- Color
- Units

### CODE REVIEW

**Comment by inimaz** [comment]
This branch is deployed in dev.

**Comment by benoit-cty** [comment]
Great !
Can you also change the color of the _energy_ trace because it quite invisible in grey on grey:
image

And add the hh:mm:ss in the tooltip ?
Because while looking at the timeseries it's important to know the time.

**Comment by SaboniAmine** [comment]
> Great ! Can you also change the color of the _energy_ trace because it quite invisible in grey on grey: 

The tooltip & the color issues are fixed in a PR I didn't push yet, also changing the run scatter chart to a time series one similar to the emissions chart

**Review by SaboniAmine — APPROVED** [review]
Thanks!

**Pull request merged**
