### PR TITLE
feat(ui): create new project

### PR DESCRIPTION
**Pull request by inimaz**
This PR allows the user to create a project under an organization page.

It contains also:
* Changes to make the modal more similar to the ones in the mockups
* Changes to reuse the modal for project tokens and project creation

Example:
image

### CODE REVIEW

**Review by SaboniAmine — APPROVED** [review]
Great work, thanks Iñigo! @mgandin here is a start of the server functions refacto, is it complying to what you wanted to do ?

**Comment by inimaz** [comment]
Thanks! Yes, it is always cool to save the API calls somewhere all together for reusability + updating them in the future. Not sure yet how to handle the `useSwr` calls though. Leaving them for now

**Comment by inimaz** [comment]
Sorry I didn't see that the last comment was directed to @mgandin  😄

**Comment by SaboniAmine** [comment]
It's alright, we can continue the discussion even with the PR closed :)

**Comment by mgandin** [comment]
> Great work, thanks Iñigo! @mgandin here is a start of the server functions refacto, is it complying to what you wanted to do ?

Yes, that was I have in mind, these kind of server functions can be very useful to expose specific endpoints for the frontend.

**Pull request merged**
