### PR TITLE
Add experiment_id to tracker-logged report

### PR DESCRIPTION
**Pull request by halsimov**
- Modify emissions_tracker.py & output.py to insert experiment_id field
- Add experiment_id in tracker tests configs

Work on #387

### CODE REVIEW

**Review by SaboniAmine — APPROVED** [review]
LGTM. Any remaining blocker @benoit-cty ?

**Comment by benoit-cty** [comment]
> LGTM. Any remaining blocker @benoit-cty ?

I personally see no blocker but the tests are broken and there is conflict with Inigo refactoring of outputs.

**Comment by SaboniAmine** [comment]
Ok lets try to merge the logfire first integration, and consider again adding experiment id to tracker. We'll come back to this PR or the other one on the same topic.

**Comment by inimaz** [comment]
Hello @halsimov,
thanks for this! In order to merge this there are minor conflicts. It is because the `EmissionsData` object has been moved here --> https://github.com/mlco2/codecarbon/blob/master/codecarbon/output_methods/emissions_data.py#L14
Could you move the experiment_id change there?

Thanks!

**Comment by halsimov** [comment]
Moved to #594

**Pull request closed without merging**
